stages:
  - terraform-apply

terraform-apply:
  stage: terraform-apply
  image:
    name: hashicorp/terraform:1.1.4
    entrypoint: [""]
  script:
    - |
      cd terraform
      terraform init
      terraform plan  -var do_token=${DO_TOKEN}
